module.exports = {
  importRegex :/.*(?=export default)/s,
  templateRegex: /<template>([\s\S]*?)<\/template>/i,
  scriptRegex: /<script>([\s\S]*?)<\/script>/i,
  styleRegex: /(<style[^>]*>[\s\S]*?<\/style>)/i,
  componentsRegExp: /compontents:\s*(\{[\s\S]*?\},)\s*/,
  componentRegExp: /compontents:\s*(\{[\s\S]*?\})\s*/i,
  dataRegExp: /data\s*\(\s*\)\s*\{\s*return\s*(\{[\s\S]*?})\s*\}\s*/i,
  mixinsRegExp: /mixins: ((\[\])|(\[([\s\S]+?)\]))[\,\n]/,
  thisKeyRegExp: /this(\.{1})([$a-zA-Z0-9_]+)/g,
  bracesRegExp: /\{[\s\S]*\}/g,
  parenthesisRegExp: /\((.*)\)/g,
  emitRegExp: /^\([\'\"\`](update:){0,1}([$a-zA-Z0-9_-]+)[\'\"\`]/,
  refRegExp: /(^\.|^\?\.)([$a-zA-Z0-9_]+)/,
};
